name: switch link

on:
  workflow_dispatch:
    inputs:
      link_acceleration:
        description: 'Enable link acceleration'
        required: true
        default: 'false'

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          acceleration_enabled="${{ secrets.LINK_ACCELERATION }}"
          if [ "$acceleration_enabled" == "true" ]; then
            sed -i 's#https://raw.githubusercontent.com/Be-Zero/PicGo/main#https://cdn.jsdelivr.net/gh/Be-Zero/PicGo@main#g' README.md
            sed -i 's#https://raw.githubusercontent.com/Be-Zero/Be-Zero/main#https://cdn.jsdelivr.net/gh/Be-Zero/Be-Zero#g' README.md
          else
            sed -i 's#https://cdn.jsdelivr.net/gh/Be-Zero/PicGo@main#https://raw.githubusercontent.com/Be-Zero/PicGo/main#g' README.md
            sed -i 's#https://cdn.jsdelivr.net/gh/Be-Zero/Be-Zero#https://raw.githubusercontent.com/Be-Zero/Be-Zero/main#g' README.md
          fi

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "switch link"
          git push
